// Pure rendering/classification for the tool-inventory generator.
// No I/O and no side effects on import, so it can be unit-tested directly.

export const START = "<!-- GEN:START — generated by scripts/gen-inventory.mjs; do not edit by hand -->";
export const END = "<!-- GEN:END -->";

// jarvis-mcp is a dynamic remote proxy — its surface is defined remotely, so it
// is described from a constant rather than introspected. Counts are approximate.
export const JARVIS = { display: "Jarvis", mcpKey: "jarvis", read: 5, write: 1, total: 6 };

export const JARVIS_SECTION = `### Remote proxy (data egress)

#### jarvis-mcp — dynamic remote proxy — **data egress**
\`jarvis-mcp\` registers **zero tools in source**. It is a pass-through proxy: it forwards \`tools/list\`, \`tools/call\`, prompts, and resources straight to the remote Jarvis MCP endpoint (\`JARVIS_BASE_URL\`, default \`https://jarvis-api.example.gov.bc.ca/mcp\`) with an \`Authorization: Bearer <JARVIS_TOKEN>\` header (\`packages/jarvis-mcp/src/index.ts\`, \`config.ts\`).

- The tool list is **whatever the remote advertises at runtime** — currently ~6: \`get_application\`, \`list_ministries\`, \`search_applications\`, \`list_technologies\`, \`get_application_provenance\` (read) and \`update_application\` (write). Treat that count as a snapshot, not a fixed contract.
- **This is the only server that proxies MCP traffic to a remote endpoint.** Every RAVEN server makes outbound calls to its upstream; what's unique to Jarvis is that it forwards opaque MCP requests/responses to a separately-hosted BC Gov API whose tool surface is defined remotely, rather than running a fixed local tool set. Relevant to the "local-only" framing and to FOIPPA/data-residency review — see \`SYSTEM_DESIGN_AND_ARCHITECTURE.md\`.`;

export const INTRO = `Servers map 1:1 to the keys in [\`../.mcp.json\`](../.mcp.json). The Atlassian-backed servers (Jira, Confluence, Bitbucket, Assets, Overview, Health, Bug Classifier) share one SiteMinder/Basic-Auth session; Server Monitor, IMIS, Azure DevOps, Sonar, Jenkins, Artifactory, RFC Buddy, and Jarvis authenticate separately via \`~/.raven/.env\`.`;

/** Split a server's tools into read / write / missing by their readOnlyHint annotation. */
export function classify(tools, ctx) {
  const read = [], write = [], missing = [];
  for (const t of tools) {
    const hint = t.annotations?.readOnlyHint;
    if (hint === true) read.push(t.name);
    else if (hint === false) write.push(t.name);
    else missing.push(`${ctx}/${t.name}`);
  }
  return { read, write, missing };
}

const fence = (names) => names.map((n) => `\`${n}\``).join(", ");
const toolsWord = (n) => (n === 1 ? "tool" : "tools");

/**
 * Render the generated markdown block from collected server data.
 * @param data Array of { display, pkg, mcpKey, group, total, read:[], write:[], note? }
 */
export function render(data, opts = {}) {
  const { jarvis = JARVIS, jarvisSection = JARVIS_SECTION, intro = INTRO } = opts;

  const localTotal = data.reduce((n, s) => n + s.total, 0);
  const localRead = data.reduce((n, s) => n + s.read.length, 0);
  const localWrite = data.reduce((n, s) => n + s.write.length, 0);
  const advertised = localTotal + jarvis.total;

  const atAGlance = [
    "## At a glance", "",
    "| | Count |", "|---|---|",
    `| MCP servers | **${data.length + 1}** |`,
    `| Tools registered locally (in-process) | **${localTotal}** |`,
    `| Tools dynamically proxied from the remote Jarvis API | **~${jarvis.total}** (not part of the ${localTotal} — see [jarvis-mcp](#jarvis-mcp--dynamic-remote-proxy--data-egress)) |`,
    `| **Tools advertised to the AI when everything is connected** | **~${advertised}** |`,
    `| Mutating / write tools | **~${localWrite + jarvis.write}** (${localWrite} local + ~${jarvis.write} via Jarvis) |`,
    `| Read-only tools | **~${localRead + jarvis.read}** |`,
    "| Non-server packages | `auth`, `pipeline`, `server-ui`, `raven-cli` |",
    "", intro,
  ];

  const summary = [
    "## Read / write summary", "",
    "| Server | `.mcp.json` key | Read | Write | Total |",
    "|--------|-----------------|-----:|------:|------:|",
    ...data.map((s) => `| ${s.display} | \`${s.mcpKey}\` | ${s.read.length} | ${s.write.length} | ${s.total} |`),
    `| **Subtotal (local)** | | **${localRead}** | **${localWrite}** | **${localTotal}** |`,
    `| Jarvis (remote proxy) | \`jarvis\` | ~${jarvis.read} | ~${jarvis.write} | ~${jarvis.total} |`,
    `| **Advertised total** | | **~${localRead + jarvis.read}** | **~${localWrite + jarvis.write}** | **~${advertised}** |`,
  ];

  const sections = ["## Servers and tools"];
  let group = null;
  for (const s of data) {
    if (s.group !== group) { group = s.group; sections.push("", `### ${group}`); }
    if (s.write.length === 0) {
      sections.push("", `#### ${s.pkg} — ${s.total} ${toolsWord(s.total)} (read-only)`, fence(s.read));
    } else {
      sections.push(
        "", `#### ${s.pkg} — ${s.total} ${toolsWord(s.total)} (${s.read.length} read / ${s.write.length} write)`,
        s.read.length ? `- **Read:** ${fence(s.read)}` : `- **Read:** _(none)_`,
        `- **Write:** ${fence(s.write)}`,
      );
    }
    if (s.note) sections.push("", `> ${s.note}`);
  }
  sections.push("", jarvisSection);

  return [atAGlance.join("\n"), summary.join("\n"), sections.join("\n")].join("\n\n");
}

/** Replace the GEN:START..GEN:END region of `file` with `body`. Throws if markers are absent. */
export function spliceRegion(file, body) {
  const startIdx = file.indexOf(START);
  const endIdx = file.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error("GEN:START / GEN:END markers not found");
  }
  return `${file.slice(0, startIdx + START.length)}\n\n${body}\n\n${file.slice(endIdx)}`;
}
